-- Replace placeholder UKMLA competencies with full condition list
-- Based on the UKMLA Conditions List (Medical Licensing Assessment, GMC)

DELETE FROM competencies WHERE curriculum = 'UKMLA';

INSERT INTO competencies (curriculum, code, name, category) VALUES

-- Cardiovascular
('UKMLA', 'CV01', 'Acute coronary syndrome (STEMI, NSTEMI, unstable angina)', 'Cardiovascular'),
('UKMLA', 'CV02', 'Aortic dissection', 'Cardiovascular'),
('UKMLA', 'CV03', 'Aortic stenosis', 'Cardiovascular'),
('UKMLA', 'CV04', 'Aortic regurgitation', 'Cardiovascular'),
('UKMLA', 'CV05', 'Atrial fibrillation and flutter', 'Cardiovascular'),
('UKMLA', 'CV06', 'Cardiac arrest', 'Cardiovascular'),
('UKMLA', 'CV07', 'Cardiac failure (acute and chronic)', 'Cardiovascular'),
('UKMLA', 'CV08', 'Cardiac tamponade', 'Cardiovascular'),
('UKMLA', 'CV09', 'Cardiomyopathy', 'Cardiovascular'),
('UKMLA', 'CV10', 'Deep vein thrombosis', 'Cardiovascular'),
('UKMLA', 'CV11', 'Endocarditis', 'Cardiovascular'),
('UKMLA', 'CV12', 'Heart block (first, second, third degree)', 'Cardiovascular'),
('UKMLA', 'CV13', 'Hypertension', 'Cardiovascular'),
('UKMLA', 'CV14', 'Hypertensive crisis', 'Cardiovascular'),
('UKMLA', 'CV15', 'Mitral regurgitation', 'Cardiovascular'),
('UKMLA', 'CV16', 'Mitral stenosis', 'Cardiovascular'),
('UKMLA', 'CV17', 'Myocarditis and pericarditis', 'Cardiovascular'),
('UKMLA', 'CV18', 'Peripheral arterial disease', 'Cardiovascular'),
('UKMLA', 'CV19', 'Pulmonary embolism', 'Cardiovascular'),
('UKMLA', 'CV20', 'Pulmonary hypertension', 'Cardiovascular'),
('UKMLA', 'CV21', 'Shock (cardiogenic, distributive, hypovolaemic, obstructive)', 'Cardiovascular'),
('UKMLA', 'CV22', 'Stable angina', 'Cardiovascular'),
('UKMLA', 'CV23', 'Supraventricular tachycardia', 'Cardiovascular'),
('UKMLA', 'CV24', 'Ventricular tachycardia and fibrillation', 'Cardiovascular'),
('UKMLA', 'CV25', 'Varicose veins and chronic venous insufficiency', 'Cardiovascular'),

-- Respiratory
('UKMLA', 'RS01', 'Asthma', 'Respiratory'),
('UKMLA', 'RS02', 'Bronchiectasis', 'Respiratory'),
('UKMLA', 'RS03', 'Chronic obstructive pulmonary disease', 'Respiratory'),
('UKMLA', 'RS04', 'Community-acquired pneumonia', 'Respiratory'),
('UKMLA', 'RS05', 'Cystic fibrosis', 'Respiratory'),
('UKMLA', 'RS06', 'Empyema', 'Respiratory'),
('UKMLA', 'RS07', 'Extrinsic allergic alveolitis', 'Respiratory'),
('UKMLA', 'RS08', 'Idiopathic pulmonary fibrosis', 'Respiratory'),
('UKMLA', 'RS09', 'Lung cancer', 'Respiratory'),
('UKMLA', 'RS10', 'Mesothelioma', 'Respiratory'),
('UKMLA', 'RS11', 'Obstructive sleep apnoea', 'Respiratory'),
('UKMLA', 'RS12', 'Pleural effusion', 'Respiratory'),
('UKMLA', 'RS13', 'Pneumothorax (spontaneous and tension)', 'Respiratory'),
('UKMLA', 'RS14', 'Pulmonary oedema', 'Respiratory'),
('UKMLA', 'RS15', 'Respiratory failure (type 1 and type 2)', 'Respiratory'),
('UKMLA', 'RS16', 'Sarcoidosis', 'Respiratory'),
('UKMLA', 'RS17', 'Tuberculosis', 'Respiratory'),
('UKMLA', 'RS18', 'Upper respiratory tract infection', 'Respiratory'),

-- Neurology
('UKMLA', 'NE01', 'Bell''s palsy', 'Neurology'),
('UKMLA', 'NE02', 'Brain tumour (primary and metastatic)', 'Neurology'),
('UKMLA', 'NE03', 'Delirium', 'Neurology'),
('UKMLA', 'NE04', 'Dementia (Alzheimer''s, vascular, Lewy body)', 'Neurology'),
('UKMLA', 'NE05', 'Epilepsy and seizures', 'Neurology'),
('UKMLA', 'NE06', 'Guillain-Barré syndrome', 'Neurology'),
('UKMLA', 'NE07', 'Headache (tension, cluster, medication overuse)', 'Neurology'),
('UKMLA', 'NE08', 'Intracerebral haemorrhage', 'Neurology'),
('UKMLA', 'NE09', 'Meningitis and encephalitis', 'Neurology'),
('UKMLA', 'NE10', 'Migraine', 'Neurology'),
('UKMLA', 'NE11', 'Motor neurone disease', 'Neurology'),
('UKMLA', 'NE12', 'Multiple sclerosis', 'Neurology'),
('UKMLA', 'NE13', 'Myasthenia gravis', 'Neurology'),
('UKMLA', 'NE14', 'Parkinson''s disease', 'Neurology'),
('UKMLA', 'NE15', 'Peripheral neuropathy', 'Neurology'),
('UKMLA', 'NE16', 'Spinal cord compression', 'Neurology'),
('UKMLA', 'NE17', 'Stroke and TIA', 'Neurology'),
('UKMLA', 'NE18', 'Subarachnoid haemorrhage', 'Neurology'),
('UKMLA', 'NE19', 'Subdural and extradural haematoma', 'Neurology'),
('UKMLA', 'NE20', 'Syncope and presyncope', 'Neurology'),

-- Gastroenterology
('UKMLA', 'GI01', 'Acute liver failure', 'Gastroenterology'),
('UKMLA', 'GI02', 'Acute pancreatitis', 'Gastroenterology'),
('UKMLA', 'GI03', 'Appendicitis', 'Gastroenterology'),
('UKMLA', 'GI04', 'Bowel obstruction (small and large)', 'Gastroenterology'),
('UKMLA', 'GI05', 'Cholecystitis and cholelithiasis', 'Gastroenterology'),
('UKMLA', 'GI06', 'Chronic liver disease and cirrhosis', 'Gastroenterology'),
('UKMLA', 'GI07', 'Chronic pancreatitis', 'Gastroenterology'),
('UKMLA', 'GI08', 'Colorectal cancer', 'Gastroenterology'),
('UKMLA', 'GI09', 'Coeliac disease', 'Gastroenterology'),
('UKMLA', 'GI10', 'Crohn''s disease', 'Gastroenterology'),
('UKMLA', 'GI11', 'Diverticular disease', 'Gastroenterology'),
('UKMLA', 'GI12', 'Gastro-oesophageal reflux disease', 'Gastroenterology'),
('UKMLA', 'GI13', 'Gastrointestinal bleeding (upper and lower)', 'Gastroenterology'),
('UKMLA', 'GI14', 'Hepatitis (viral, alcoholic, autoimmune)', 'Gastroenterology'),
('UKMLA', 'GI15', 'Hernias (inguinal, femoral, incisional, hiatus)', 'Gastroenterology'),
('UKMLA', 'GI16', 'Irritable bowel syndrome', 'Gastroenterology'),
('UKMLA', 'GI17', 'Oesophageal cancer', 'Gastroenterology'),
('UKMLA', 'GI18', 'Pancreatic cancer', 'Gastroenterology'),
('UKMLA', 'GI19', 'Peptic ulcer disease', 'Gastroenterology'),
('UKMLA', 'GI20', 'Peritonitis', 'Gastroenterology'),
('UKMLA', 'GI21', 'Ulcerative colitis', 'Gastroenterology'),

-- Endocrinology & Metabolism
('UKMLA', 'EN01', 'Addison''s disease', 'Endocrinology'),
('UKMLA', 'EN02', 'Cushing''s syndrome', 'Endocrinology'),
('UKMLA', 'EN03', 'Diabetic ketoacidosis', 'Endocrinology'),
('UKMLA', 'EN04', 'Hyperosmolar hyperglycaemic state', 'Endocrinology'),
('UKMLA', 'EN05', 'Hyperthyroidism and thyrotoxicosis', 'Endocrinology'),
('UKMLA', 'EN06', 'Hypoglycaemia', 'Endocrinology'),
('UKMLA', 'EN07', 'Hyponatraemia and hypernatraemia', 'Endocrinology'),
('UKMLA', 'EN08', 'Hypokalaemia and hyperkalaemia', 'Endocrinology'),
('UKMLA', 'EN09', 'Hypothyroidism and myxoedema', 'Endocrinology'),
('UKMLA', 'EN10', 'Obesity', 'Endocrinology'),
('UKMLA', 'EN11', 'Osteoporosis', 'Endocrinology'),
('UKMLA', 'EN12', 'Phaeochromocytoma', 'Endocrinology'),
('UKMLA', 'EN13', 'Primary hyperaldosteronism', 'Endocrinology'),
('UKMLA', 'EN14', 'Type 1 diabetes mellitus', 'Endocrinology'),
('UKMLA', 'EN15', 'Type 2 diabetes mellitus', 'Endocrinology'),

-- Renal & Urology
('UKMLA', 'RN01', 'Acute kidney injury', 'Renal'),
('UKMLA', 'RN02', 'Benign prostatic hyperplasia', 'Renal'),
('UKMLA', 'RN03', 'Bladder cancer', 'Renal'),
('UKMLA', 'RN04', 'Chronic kidney disease', 'Renal'),
('UKMLA', 'RN05', 'Glomerulonephritis', 'Renal'),
('UKMLA', 'RN06', 'Nephrotic and nephritic syndrome', 'Renal'),
('UKMLA', 'RN07', 'Prostate cancer', 'Renal'),
('UKMLA', 'RN08', 'Renal calculi', 'Renal'),
('UKMLA', 'RN09', 'Renal cell carcinoma', 'Renal'),
('UKMLA', 'RN10', 'Testicular torsion and cancer', 'Renal'),
('UKMLA', 'RN11', 'Urinary tract infection (lower and upper)', 'Renal'),
('UKMLA', 'RN12', 'Urinary incontinence', 'Renal'),

-- Musculoskeletal
('UKMLA', 'MS01', 'Ankylosing spondylitis', 'Musculoskeletal'),
('UKMLA', 'MS02', 'Back pain (mechanical and serious causes)', 'Musculoskeletal'),
('UKMLA', 'MS03', 'Carpal tunnel syndrome', 'Musculoskeletal'),
('UKMLA', 'MS04', 'Compartment syndrome', 'Musculoskeletal'),
('UKMLA', 'MS05', 'Crystal arthropathy (gout and pseudogout)', 'Musculoskeletal'),
('UKMLA', 'MS06', 'Fractures (common types and management)', 'Musculoskeletal'),
('UKMLA', 'MS07', 'Osteoarthritis', 'Musculoskeletal'),
('UKMLA', 'MS08', 'Osteomyelitis', 'Musculoskeletal'),
('UKMLA', 'MS09', 'Paget''s disease of bone', 'Musculoskeletal'),
('UKMLA', 'MS10', 'Psoriatic arthritis', 'Musculoskeletal'),
('UKMLA', 'MS11', 'Reactive arthritis', 'Musculoskeletal'),
('UKMLA', 'MS12', 'Rheumatoid arthritis', 'Musculoskeletal'),
('UKMLA', 'MS13', 'Septic arthritis', 'Musculoskeletal'),
('UKMLA', 'MS14', 'Systemic lupus erythematosus', 'Musculoskeletal'),
('UKMLA', 'MS15', 'Vasculitis (GCA, GPA, polyarteritis nodosa)', 'Musculoskeletal'),

-- Haematology & Oncology
('UKMLA', 'HM01', 'Anaemia (iron deficiency, B12/folate, haemolytic)', 'Haematology'),
('UKMLA', 'HM02', 'Anticoagulation and bleeding disorders', 'Haematology'),
('UKMLA', 'HM03', 'Chronic myeloid leukaemia', 'Haematology'),
('UKMLA', 'HM04', 'Disseminated intravascular coagulation', 'Haematology'),
('UKMLA', 'HM05', 'Hodgkin''s and non-Hodgkin''s lymphoma', 'Haematology'),
('UKMLA', 'HM06', 'Leukaemia (ALL, AML, CLL)', 'Haematology'),
('UKMLA', 'HM07', 'Multiple myeloma', 'Haematology'),
('UKMLA', 'HM08', 'Myeloproliferative disorders', 'Haematology'),
('UKMLA', 'HM09', 'Sickle cell disease', 'Haematology'),
('UKMLA', 'HM10', 'Thalassaemia', 'Haematology'),
('UKMLA', 'HM11', 'Thrombocytopenia (ITP, TTP)', 'Haematology'),
('UKMLA', 'HM12', 'Transfusion reactions', 'Haematology'),

-- Infectious Disease
('UKMLA', 'ID01', 'COVID-19 and post-COVID syndrome', 'Infectious Disease'),
('UKMLA', 'ID02', 'HIV and AIDS', 'Infectious Disease'),
('UKMLA', 'ID03', 'Infective endocarditis', 'Infectious Disease'),
('UKMLA', 'ID04', 'Malaria', 'Infectious Disease'),
('UKMLA', 'ID05', 'Neutropenic sepsis', 'Infectious Disease'),
('UKMLA', 'ID06', 'Sepsis and septic shock', 'Infectious Disease'),
('UKMLA', 'ID07', 'Sexually transmitted infections', 'Infectious Disease'),
('UKMLA', 'ID08', 'Skin and soft tissue infections (cellulitis, necrotising fasciitis)', 'Infectious Disease'),

-- Mental Health
('UKMLA', 'MH01', 'Acute psychosis', 'Mental Health'),
('UKMLA', 'MH02', 'Alcohol use disorder and withdrawal', 'Mental Health'),
('UKMLA', 'MH03', 'Anorexia nervosa and bulimia nervosa', 'Mental Health'),
('UKMLA', 'MH04', 'Anxiety disorders (GAD, panic disorder, phobias)', 'Mental Health'),
('UKMLA', 'MH05', 'Bipolar affective disorder', 'Mental Health'),
('UKMLA', 'MH06', 'Depression', 'Mental Health'),
('UKMLA', 'MH07', 'Obsessive-compulsive disorder', 'Mental Health'),
('UKMLA', 'MH08', 'Personality disorders', 'Mental Health'),
('UKMLA', 'MH09', 'Post-traumatic stress disorder', 'Mental Health'),
('UKMLA', 'MH10', 'Schizophrenia', 'Mental Health'),
('UKMLA', 'MH11', 'Self-harm and suicide risk assessment', 'Mental Health'),
('UKMLA', 'MH12', 'Substance misuse disorders', 'Mental Health'),

-- Obstetrics & Gynaecology
('UKMLA', 'OG01', 'Antepartum haemorrhage (placenta praevia, abruption)', 'Obs & Gynae'),
('UKMLA', 'OG02', 'Cervical cancer and smear abnormalities', 'Obs & Gynae'),
('UKMLA', 'OG03', 'Ectopic pregnancy', 'Obs & Gynae'),
('UKMLA', 'OG04', 'Endometriosis', 'Obs & Gynae'),
('UKMLA', 'OG05', 'Gestational diabetes', 'Obs & Gynae'),
('UKMLA', 'OG06', 'Hyperemesis gravidarum', 'Obs & Gynae'),
('UKMLA', 'OG07', 'Miscarriage and recurrent pregnancy loss', 'Obs & Gynae'),
('UKMLA', 'OG08', 'Ovarian cancer', 'Obs & Gynae'),
('UKMLA', 'OG09', 'Ovarian cysts and torsion', 'Obs & Gynae'),
('UKMLA', 'OG10', 'Pelvic inflammatory disease', 'Obs & Gynae'),
('UKMLA', 'OG11', 'Polycystic ovary syndrome', 'Obs & Gynae'),
('UKMLA', 'OG12', 'Post-partum haemorrhage', 'Obs & Gynae'),
('UKMLA', 'OG13', 'Pre-eclampsia and eclampsia', 'Obs & Gynae'),
('UKMLA', 'OG14', 'Preterm labour', 'Obs & Gynae'),
('UKMLA', 'OG15', 'Uterine fibroids', 'Obs & Gynae'),

-- Paediatrics
('UKMLA', 'PD01', 'Bronchiolitis', 'Paediatrics'),
('UKMLA', 'PD02', 'Child safeguarding and non-accidental injury', 'Paediatrics'),
('UKMLA', 'PD03', 'Congenital heart disease', 'Paediatrics'),
('UKMLA', 'PD04', 'Croup and epiglottitis', 'Paediatrics'),
('UKMLA', 'PD05', 'Developmental delay and assessment', 'Paediatrics'),
('UKMLA', 'PD06', 'Febrile convulsions', 'Paediatrics'),
('UKMLA', 'PD07', 'Meningococcal disease', 'Paediatrics'),
('UKMLA', 'PD08', 'Neonatal jaundice', 'Paediatrics'),
('UKMLA', 'PD09', 'Neonatal resuscitation', 'Paediatrics'),
('UKMLA', 'PD10', 'Paediatric asthma', 'Paediatrics'),
('UKMLA', 'PD11', 'Pyloric stenosis', 'Paediatrics'),
('UKMLA', 'PD12', 'Sudden infant death syndrome', 'Paediatrics'),
('UKMLA', 'PD13', 'Type 1 diabetes in children', 'Paediatrics'),

-- Dermatology
('UKMLA', 'DM01', 'Acne vulgaris', 'Dermatology'),
('UKMLA', 'DM02', 'Basal cell carcinoma', 'Dermatology'),
('UKMLA', 'DM03', 'Burns assessment and management', 'Dermatology'),
('UKMLA', 'DM04', 'Eczema (atopic dermatitis)', 'Dermatology'),
('UKMLA', 'DM05', 'Melanoma', 'Dermatology'),
('UKMLA', 'DM06', 'Psoriasis', 'Dermatology'),
('UKMLA', 'DM07', 'Rosacea', 'Dermatology'),
('UKMLA', 'DM08', 'Squamous cell carcinoma', 'Dermatology'),
('UKMLA', 'DM09', 'Stevens-Johnson syndrome and toxic epidermal necrolysis', 'Dermatology'),
('UKMLA', 'DM10', 'Urticaria and angioedema', 'Dermatology'),

-- Ophthalmology & ENT
('UKMLA', 'OE01', 'Acute angle-closure glaucoma', 'Ophthalmology & ENT'),
('UKMLA', 'OE02', 'Cataract', 'Ophthalmology & ENT'),
('UKMLA', 'OE03', 'Epiglottitis', 'Ophthalmology & ENT'),
('UKMLA', 'OE04', 'Epistaxis', 'Ophthalmology & ENT'),
('UKMLA', 'OE05', 'Macular degeneration', 'Ophthalmology & ENT'),
('UKMLA', 'OE06', 'Otitis media and externa', 'Ophthalmology & ENT'),
('UKMLA', 'OE07', 'Retinal detachment', 'Ophthalmology & ENT'),
('UKMLA', 'OE08', 'Sudden painless loss of vision', 'Ophthalmology & ENT'),
('UKMLA', 'OE09', 'Tonsillitis and peritonsillar abscess', 'Ophthalmology & ENT'),
('UKMLA', 'OE10', 'Vertigo and labyrinthitis', 'Ophthalmology & ENT'),

-- Clinical Skills & Professionalism
('UKMLA', 'CS01', 'Capacity assessment and consent', 'Clinical Skills'),
('UKMLA', 'CS02', 'Breaking bad news', 'Clinical Skills'),
('UKMLA', 'CS03', 'Death certification and verification', 'Clinical Skills'),
('UKMLA', 'CS04', 'Drug prescribing and pharmacovigilance', 'Clinical Skills'),
('UKMLA', 'CS05', 'End of life care and palliative management', 'Clinical Skills'),
('UKMLA', 'CS06', 'Fluid and electrolyte management', 'Clinical Skills'),
('UKMLA', 'CS07', 'Handover and escalation (SBAR)', 'Clinical Skills'),
('UKMLA', 'CS08', 'Oxygen therapy and airway management', 'Clinical Skills'),
('UKMLA', 'CS09', 'Pain management', 'Clinical Skills'),
('UKMLA', 'CS10', 'Safeguarding adults', 'Clinical Skills');
