-- Replace placeholder exam syllabi with real published content
-- Sources: GMC MSRA blueprint, MRCS Part A syllabus, MRCP Part 1 syllabus,
--          MRCGP AKT blueprint, MRCEM Primary syllabus

DELETE FROM exam_syllabi;

-- =============================================
-- MSRA (Multi-Specialty Recruitment Assessment)
-- =============================================
INSERT INTO exam_syllabi (exam, topic, subtopic, tags) VALUES
('MSRA', 'Cardiology', 'Acute coronary syndromes', ARRAY['ECG', 'troponin', 'STEMI', 'NSTEMI']),
('MSRA', 'Cardiology', 'Arrhythmias and ECG interpretation', ARRAY['AF', 'heart block', 'SVT', 'VT']),
('MSRA', 'Cardiology', 'Heart failure management', ARRAY['diuretics', 'ACEi', 'beta-blockers']),
('MSRA', 'Cardiology', 'Hypertension', ARRAY['antihypertensives', 'target organ damage']),
('MSRA', 'Respiratory', 'Asthma (acute and chronic management)', ARRAY['BTS guidelines', 'stepwise treatment']),
('MSRA', 'Respiratory', 'COPD exacerbations', ARRAY['NIV', 'controlled oxygen', 'ABG']),
('MSRA', 'Respiratory', 'Pneumonia (CAP and HAP)', ARRAY['CURB-65', 'antibiotics', 'SIADH']),
('MSRA', 'Respiratory', 'Pulmonary embolism', ARRAY['Wells score', 'CTPA', 'anticoagulation']),
('MSRA', 'Gastroenterology', 'Upper GI bleeding', ARRAY['Rockall score', 'endoscopy', 'PPI']),
('MSRA', 'Gastroenterology', 'Inflammatory bowel disease', ARRAY['Crohn''s', 'UC', 'biologics']),
('MSRA', 'Gastroenterology', 'Liver disease', ARRAY['cirrhosis', 'ascites', 'SBP', 'hepatic encephalopathy']),
('MSRA', 'Gastroenterology', 'Acute pancreatitis', ARRAY['Glasgow criteria', 'ERCP', 'fluid resuscitation']),
('MSRA', 'Neurology', 'Stroke and TIA management', ARRAY['thrombolysis', 'NIHSS', 'secondary prevention']),
('MSRA', 'Neurology', 'Epilepsy and status epilepticus', ARRAY['AED', 'NICE guidelines', 'driving restrictions']),
('MSRA', 'Neurology', 'Headache syndromes', ARRAY['migraine', 'cluster', 'SAH', 'red flags']),
('MSRA', 'Endocrinology', 'Diabetes management (type 1 and 2)', ARRAY['HbA1c targets', 'DKA', 'HHS', 'SGLT2i']),
('MSRA', 'Endocrinology', 'Thyroid disorders', ARRAY['hypothyroidism', 'hyperthyroidism', 'thyroid storm']),
('MSRA', 'Endocrinology', 'Adrenal insufficiency', ARRAY['Addisonian crisis', 'hydrocortisone', 'sick day rules']),
('MSRA', 'Renal', 'Acute kidney injury', ARRAY['KDIGO staging', 'AKIN criteria', 'dialysis indications']),
('MSRA', 'Renal', 'Chronic kidney disease', ARRAY['eGFR', 'proteinuria', 'renal anaemia']),
('MSRA', 'Renal', 'Electrolyte disturbances', ARRAY['hyponatraemia', 'hyperkalaemia', 'ECG changes']),
('MSRA', 'Haematology', 'Anaemia (investigation and management)', ARRAY['iron', 'B12', 'folate', 'haemolysis']),
('MSRA', 'Haematology', 'Anticoagulation management', ARRAY['warfarin', 'DOACs', 'reversal agents']),
('MSRA', 'Haematology', 'Thrombocytopenia', ARRAY['ITP', 'TTP', 'HIT']),
('MSRA', 'Infectious Disease', 'Sepsis recognition and management', ARRAY['Sepsis-3', 'sepsis 6', 'blood cultures']),
('MSRA', 'Infectious Disease', 'Meningitis', ARRAY['bacterial', 'viral', 'LP', 'dexamethasone']),
('MSRA', 'Infectious Disease', 'HIV management', ARRAY['ART', 'opportunistic infections', 'PEP/PrEP']),
('MSRA', 'Mental Health', 'Depression and anxiety disorders', ARRAY['PHQ-9', 'GAD-7', 'SSRIs', 'CBT']),
('MSRA', 'Mental Health', 'Psychosis and schizophrenia', ARRAY['antipsychotics', 'MSE', 'MHA sections']),
('MSRA', 'Mental Health', 'Suicide risk assessment', ARRAY['Columbia scale', 'safe messaging', 'MHA']),
('MSRA', 'Pharmacology', 'Adverse drug reactions and interactions', ARRAY['QT prolongation', 'serotonin syndrome', 'NMS']),
('MSRA', 'Pharmacology', 'Safe prescribing principles', ARRAY['renal dosing', 'hepatic dosing', 'BNF']),
('MSRA', 'Clinical Ethics', 'Consent and capacity', ARRAY['MCA 2005', 'Gillick competence', 'best interests']),
('MSRA', 'Clinical Ethics', 'End of life decision making', ARRAY['DNAR', 'ADRT', 'best interests']),
('MSRA', 'Professionalism', 'Duty of candour', ARRAY['GMC guidance', 'error disclosure', 'apology']),
('MSRA', 'Professionalism', 'Raising concerns (whistleblowing)', ARRAY['Freedom to Speak Up', 'GMC guidance']),

-- =============================================
-- MRCS Part A (Royal College of Surgeons)
-- =============================================
('MRCS Part A', 'Applied Surgical Anatomy', 'Head and neck anatomy', ARRAY['cranial nerves', 'triangles of neck', 'parotid']),
('MRCS Part A', 'Applied Surgical Anatomy', 'Thoracic anatomy', ARRAY['mediastinum', 'chest wall', 'diaphragm']),
('MRCS Part A', 'Applied Surgical Anatomy', 'Abdominal anatomy', ARRAY['peritoneum', 'retroperitoneum', 'inguinal canal']),
('MRCS Part A', 'Applied Surgical Anatomy', 'Vascular anatomy', ARRAY['aorta', 'iliacs', 'femoral triangle']),
('MRCS Part A', 'Applied Surgical Anatomy', 'Limb anatomy', ARRAY['brachial plexus', 'dermatomes', 'compartments']),
('MRCS Part A', 'Physiology', 'Fluid and electrolyte physiology', ARRAY['Starling forces', 'osmolality', 'SIADH']),
('MRCS Part A', 'Physiology', 'Cardiovascular physiology', ARRAY['cardiac output', 'Starling law', 'peripheral resistance']),
('MRCS Part A', 'Physiology', 'Respiratory physiology', ARRAY['V/Q ratio', 'dead space', 'compliance']),
('MRCS Part A', 'Physiology', 'Renal physiology', ARRAY['GFR', 'tubular reabsorption', 'acid-base']),
('MRCS Part A', 'Physiology', 'Wound healing and repair', ARRAY['primary intention', 'fibrosis', 'keloid']),
('MRCS Part A', 'Pathology', 'Surgical oncology principles', ARRAY['TNM staging', 'margins', 'lymph node dissection']),
('MRCS Part A', 'Pathology', 'Inflammation and infection', ARRAY['SIRS', 'sepsis', 'abscess formation']),
('MRCS Part A', 'Pathology', 'Neoplasia', ARRAY['invasion', 'metastasis', 'tumour markers']),
('MRCS Part A', 'Pharmacology', 'Anaesthetic agents', ARRAY['volatile agents', 'TIVA', 'muscle relaxants']),
('MRCS Part A', 'Pharmacology', 'Analgesic ladder', ARRAY['WHO ladder', 'opioids', 'NSAIDs', 'adjuvants']),
('MRCS Part A', 'Pharmacology', 'Antibiotics in surgery', ARRAY['prophylaxis', 'de-escalation', 'resistance']),
('MRCS Part A', 'Critical Care', 'Shock recognition and management', ARRAY['haemorrhagic', 'distributive', 'obstructive']),
('MRCS Part A', 'Critical Care', 'Nutritional support in surgery', ARRAY['NG feeding', 'TPN', 'ERAS protocol']),
('MRCS Part A', 'Critical Care', 'Postoperative complications', ARRAY['DVT', 'PE', 'anastomotic leak', 'SSI']),
('MRCS Part A', 'Microbiology', 'Surgical site infections', ARRAY['classification', 'organisms', 'prevention']),
('MRCS Part A', 'Microbiology', 'Clostridium difficile', ARRAY['risk factors', 'metronidazole', 'fidaxomicin']),

-- =============================================
-- MRCP Part 1 (Royal College of Physicians)
-- =============================================
('MRCP Part 1', 'Cardiology', 'Ischaemic heart disease', ARRAY['TIMI score', 'PCI', 'CABG indications']),
('MRCP Part 1', 'Cardiology', 'Valvular heart disease', ARRAY['murmurs', 'echo findings', 'surgery indications']),
('MRCP Part 1', 'Cardiology', 'Cardiomyopathies', ARRAY['HCM', 'DCM', 'ARVC', 'Brugada']),
('MRCP Part 1', 'Cardiology', 'Pericardial disease', ARRAY['pericarditis', 'effusion', 'tamponade']),
('MRCP Part 1', 'Respiratory Medicine', 'Interstitial lung disease', ARRAY['UIP', 'NSIP', 'BAL findings']),
('MRCP Part 1', 'Respiratory Medicine', 'Pleural disease', ARRAY['Light''s criteria', 'mesothelioma', 'drainage']),
('MRCP Part 1', 'Respiratory Medicine', 'Lung cancer', ARRAY['staging', 'paraneoplastic syndromes', 'treatment']),
('MRCP Part 1', 'Gastroenterology', 'Malabsorption syndromes', ARRAY['coeliac', 'tropical sprue', 'SIBO']),
('MRCP Part 1', 'Gastroenterology', 'Hepatology', ARRAY['Child-Pugh', 'MELD', 'spontaneous bacterial peritonitis']),
('MRCP Part 1', 'Gastroenterology', 'Colorectal conditions', ARRAY['IBD', 'polyps', 'Lynch syndrome']),
('MRCP Part 1', 'Neurology', 'Movement disorders', ARRAY['Parkinson''s', 'essential tremor', 'Huntington''s']),
('MRCP Part 1', 'Neurology', 'Demyelinating disease', ARRAY['MS phenotypes', 'NMO', 'DMTs']),
('MRCP Part 1', 'Neurology', 'Neuromuscular disease', ARRAY['MND', 'myasthenia', 'Guillain-Barré']),
('MRCP Part 1', 'Endocrinology', 'Pituitary disorders', ARRAY['acromegaly', 'Cushing''s disease', 'prolactinoma']),
('MRCP Part 1', 'Endocrinology', 'Calcium and bone disorders', ARRAY['hyperparathyroidism', 'osteoporosis', 'Paget''s']),
('MRCP Part 1', 'Endocrinology', 'MEN syndromes', ARRAY['MEN1', 'MEN2a', 'MEN2b']),
('MRCP Part 1', 'Rheumatology', 'Connective tissue diseases', ARRAY['SLE', 'Sjogren''s', 'scleroderma']),
('MRCP Part 1', 'Rheumatology', 'Inflammatory arthritis', ARRAY['RA', 'AS', 'psoriatic arthritis', 'DMARDs']),
('MRCP Part 1', 'Rheumatology', 'Vasculitis', ARRAY['ANCA', 'GCA', 'Takayasu', 'PAN']),
('MRCP Part 1', 'Haematology', 'Myeloproliferative disorders', ARRAY['PCV', 'ET', 'myelofibrosis', 'JAK2']),
('MRCP Part 1', 'Haematology', 'Lymphoproliferative disorders', ARRAY['CLL', 'lymphoma', 'myeloma']),
('MRCP Part 1', 'Haematology', 'Coagulation disorders', ARRAY['haemophilia', 'vWD', 'DIC', 'TTP']),
('MRCP Part 1', 'Nephrology', 'Glomerular disease', ARRAY['nephrotic', 'nephritic', 'biopsy findings']),
('MRCP Part 1', 'Nephrology', 'Renal tubular disorders', ARRAY['RTA', 'Fanconi syndrome', 'Bartter''s']),
('MRCP Part 1', 'Dermatology', 'Systemic disease and skin', ARRAY['necrobiosis lipoidica', 'pyoderma', 'dermatomyositis']),
('MRCP Part 1', 'Oncology', 'Paraneoplastic syndromes', ARRAY['SIADH', 'hypercalcaemia', 'Lambert-Eaton']),
('MRCP Part 1', 'Pharmacology', 'Drug-induced disease', ARRAY['SJS', 'drug-induced lupus', 'agranulocytosis']),
('MRCP Part 1', 'Statistics', 'Clinical trial design and interpretation', ARRAY['NNT', 'NNH', 'sensitivity', 'specificity']),

-- =============================================
-- MRCGP AKT (Applied Knowledge Test)
-- =============================================
('MRCGP AKT', 'Clinical Medicine', 'Common presentations in primary care', ARRAY['chest pain', 'breathlessness', 'abdominal pain']),
('MRCGP AKT', 'Clinical Medicine', 'Chronic disease management', ARRAY['QOF', 'NICE guidelines', 'recall systems']),
('MRCGP AKT', 'Clinical Medicine', 'Cancer recognition and referral', ARRAY['2-week wait', 'NICE NG12', 'red flags']),
('MRCGP AKT', 'Clinical Medicine', 'Paediatric presentations', ARRAY['NICE feverish illness', 'safeguarding', 'developmental milestones']),
('MRCGP AKT', 'Clinical Medicine', 'Mental health in primary care', ARRAY['PHQ-9', 'IAPT', 'CMHT referral']),
('MRCGP AKT', 'Clinical Medicine', 'Women''s health', ARRAY['contraception', 'menopause', 'cervical screening']),
('MRCGP AKT', 'Clinical Medicine', 'Men''s health', ARRAY['PSA', 'erectile dysfunction', 'testicular examination']),
('MRCGP AKT', 'Prescribing', 'Repeat prescribing and polypharmacy', ARRAY['medication review', 'deprescribing', 'STOPP/START']),
('MRCGP AKT', 'Prescribing', 'Drug interactions in primary care', ARRAY['warfarin', 'statins', 'SSRIs']),
('MRCGP AKT', 'Prescribing', 'Controlled drugs', ARRAY['opioid prescribing', 'CD regulations', 'addiction']),
('MRCGP AKT', 'Evidence and Statistics', 'Evidence-based medicine', ARRAY['systematic review', 'meta-analysis', 'RCT']),
('MRCGP AKT', 'Evidence and Statistics', 'Interpreting research papers', ARRAY['p-value', 'confidence interval', 'bias']),
('MRCGP AKT', 'Evidence and Statistics', 'Screening programmes', ARRAY['Wilson criteria', 'PPV', 'NPV']),
('MRCGP AKT', 'Organisational', 'NHS structure and commissioning', ARRAY['ICB', 'PCN', 'CQC']),
('MRCGP AKT', 'Organisational', 'Quality and patient safety', ARRAY['significant event analysis', 'root cause analysis']),
('MRCGP AKT', 'Organisational', 'Information governance', ARRAY['GDPR', 'Caldicott principles', 'data sharing']),
('MRCGP AKT', 'Ethical and Legal', 'Confidentiality in general practice', ARRAY['Fraser guidelines', 'Caldicott', 'disclosure']),
('MRCGP AKT', 'Ethical and Legal', 'Fitness to drive (DVLA)', ARRAY['Group 1', 'Group 2', 'notifiable conditions']),
('MRCGP AKT', 'Ethical and Legal', 'Certification and reports', ARRAY['Med 3', 'insurance reports', 'cremation forms']),

-- =============================================
-- MRCEM Primary (Emergency Medicine)
-- =============================================
('MRCEM Primary', 'Anatomy', 'Airway anatomy', ARRAY['larynx', 'trachea', 'cricothyroid membrane']),
('MRCEM Primary', 'Anatomy', 'Thoracic anatomy for procedures', ARRAY['pleural space', 'intercostal space', 'pericardium']),
('MRCEM Primary', 'Anatomy', 'Vascular access anatomy', ARRAY['IJV', 'subclavian', 'femoral vein']),
('MRCEM Primary', 'Anatomy', 'Lower limb compartments', ARRAY['fasciotomy', 'compartment syndrome', 'nerve supply']),
('MRCEM Primary', 'Physiology', 'Respiratory physiology', ARRAY['minute ventilation', 'dead space', 'hypoxic drive']),
('MRCEM Primary', 'Physiology', 'Cardiovascular physiology', ARRAY['preload', 'afterload', 'contractility']),
('MRCEM Primary', 'Physiology', 'Acid-base physiology', ARRAY['Henderson-Hasselbalch', 'compensation', 'base excess']),
('MRCEM Primary', 'Physiology', 'Shock physiology', ARRAY['oxygen delivery', 'cellular hypoxia', 'compensatory mechanisms']),
('MRCEM Primary', 'Pharmacology', 'Emergency pharmacology', ARRAY['adrenaline', 'atropine', 'adenosine', 'amiodarone']),
('MRCEM Primary', 'Pharmacology', 'Sedation and anaesthesia', ARRAY['ketamine', 'propofol', 'midazolam', 'RSI']),
('MRCEM Primary', 'Pharmacology', 'Analgesia in emergency medicine', ARRAY['IV morphine', 'intranasal fentanyl', 'nerve blocks']),
('MRCEM Primary', 'Pathology', 'Trauma pathophysiology', ARRAY['coagulopathy', 'hypothermia', 'acidosis', 'lethal triad']),
('MRCEM Primary', 'Pathology', 'Toxicology', ARRAY['paracetamol overdose', 'NAC', 'TOXBASE']),
('MRCEM Primary', 'Pathology', 'Infection and inflammation', ARRAY['SIRS', 'sepsis-3', 'source control']),
('MRCEM Primary', 'Clinical', 'Major trauma management', ARRAY['ATLS', 'primary survey', 'damage control']),
('MRCEM Primary', 'Clinical', 'Paediatric emergencies', ARRAY['Paediatric Early Warning Score', 'fluid resuscitation', 'safeguarding']),
('MRCEM Primary', 'Clinical', 'Obstetric emergencies', ARRAY['eclampsia', 'PPH', 'shoulder dystocia']),
('MRCEM Primary', 'Clinical', 'Psychiatric emergencies', ARRAY['MHA assessment', 'rapid tranquillisation', 'de-escalation']);
